apiVersion: v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: django
        image: adminsmart/django:latest
        command: ["./start.sh"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"        


---


apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    role: django
    app: django